### ISSUE TITLE
If I try this with the latest jekyll 3 beta 8 get several Liquid exceptions 

### ISSUE THREAD

**Issue by xicubed** [st4ple/solid-jekyll#12]
If I manually remove the offending ones I can find, the site's css still doesn't build for another liquid exception.

$ jekyll serve
Configuration file: /Users/blablabla/_config.yml
            Source: /Users/blablabla
       Destination: /Users/blablabla/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: Liquid syntax error: Unexpected character   in "{{ site.email }}" in contact.html
jekyll 3.0.0.pre.beta8 | Error:  Liquid syntax error: Unexpected character   in "{{ site.email }}"

**Comment by tmas** [comment]
This seems to have been fixed in newer versions of Jekyll, although there's still one warning on build (which I'm about to submit a pull request to fix)
