### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by joostrijneveld** [st4ple/solid-jekyll#26]
This is a cool project, but as it is right now, it has not been clearly licensed. This is especially interesting since it is a port of an existing work (i.e. the [Solid theme](http://blacktie.co/2014/05/solid-multipurpose-theme/)). The [original theme is licensed](http://blacktie.co/about-themes/) as [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) (which does not allow sublicensing), but you'd license the additional work. It may make things easier to just go with CC BY 3.0 as well.

**Comment by ShaneCurcuru** [comment]
Very clean yet snazzy and rich theme - I'd love to use it as well, but I won't use code without a license.  If the underlying code is really CC BY 3.0, just use that here.  Alternately, for more advice on licenses, https://choosealicense.com is great.

**Comment by jacksonrayhamilton** [comment]
Agreed, we'd love to use this, but need clearly-defined license terms.

**Comment by sonalkr132** [comment]
Same here :( This looks like a theme we can use but I can't use it unless license is stated.

**Comment by st4ple** [comment]
license is set since ea8a99205003001ed04c2a3be9e1824ab5e90ccb
