### ISSUE TITLE
Using solid theme as github.io website

### ISSUE THREAD

**Issue by ramitsurana** [st4ple/solid-jekyll#28]
Hi,
I am trying to work with this theme on https://github.com/coolhacks/coolhacks.github.io.
I have tried to changing the _.config.yml I have updated the url and the base url many times but still no effect.The images and the css theme do not load at all.If anybody knows what part I am doing wrong please let me know.Thanks a lot.

**Comment by tmas** [comment]
I can't be certain for this theme specifically, but I know other themes that have you specify a URL in the _config.yml have documentation saying that it won't work with Github Pages. You can always compile the site on your computer and upload the result to Github.
