### ISSUE TITLE
Page doesnot look the same as in the demo

### ISSUE THREAD

**Issue by sigvoiced** [st4ple/solid-jekyll#44]
After forking the repository as it is, I looked at the page and it does not look the same. 
[https://sigvoiced.github.io/](https://sigvoiced.github.io/) is the link to my github page incase you want to see what has happened.

I am not sure about the issue. It would be great if anyone could help.

**Comment by tanay-bits** [comment]
What's baseurl and url in your _config.yml file? Try these two options, push them online and see if either helps:

- Make the baseurl blank. `baseurl: ""`, or
- Write the name of your repository starting with / in basurl. `baseurl: "/<your_repo_name>"`

**Comment by tanay-bits** [comment]
#45

**Comment by sigvoiced** [comment]
Thanks a lot. Works now. Can't imagine it was such a minor thing and I wasted numerous hours trying to look for what went wrong. I would still like to know, how did just a rename fix the issue? What is wrong with style.css?

**Comment by aulon** [comment]
I made the same change but my website looks different from the template.
![selection_023](https://cloud.githubusercontent.com/assets/8798414/25411399/c46e7834-2a1c-11e7-8f7a-6da3dde84e1d.png)

**Comment by daviddavo** [comment]
Same for me :/

**Comment by nniiicc** [comment]
@daviddavo it looks like you got the theme to load properly - how did you solve the problem?

**Comment by Kevin-Middleton** [comment]
@nniiicc Also have the same problem - trying to figure out what @daviddavo did to fix his.

**Comment by daviddavo** [comment]
You have to rename style.css to "whatever.css" and edit every file that uses that file

**Comment by navoshta** [comment]
You guys saved my bacon.
