### ISSUE TITLE
CSS not rendering anymore, when earlier it was perfect

### ISSUE THREAD

**Issue by tanay-bits** [st4ple/solid-jekyll#45]
My page - [http://tanay-bits.github.io/](http://tanay-bits.github.io/) was working just fine, but recently the CSS elements have stopped loading, without any changes from my side. My fork is at [https://github.com/tanay-bits/tanay-bits.github.io](http://github.com/tanay-bits/tanay-bits.github.io ).

If anyone has any idea what's going on here, or if it's this theme or GitHub Pages in general which could be the cause, please help out.

**Comment by MichaelMMeskhi** [comment]
Same issue.

**Comment by Pluu** [comment]
This Fixed Issues. CSS file rename.
@tanay-bits @MichaelMMeskhi  This Commit Check. 
https://github.com/Pluu/pluu.github.io/commit/d66a9ef6586e7cd207172e683721cd958ed10150

**Comment by tanay-bits** [comment]
@Pluu Thank you so much! This saved me days of needless toiling switching to a different theme. You should make a pull request.
