### ISSUE TITLE
Problems with javascript 

### ISSUE THREAD

**Issue by esmartwave** [st4ple/solid-jekyll#47]
I followed the install instructions and forked the theme (which looks great, btw) to this repo: 
https://github.com/milwaukeedata/solid-jekyll

Which is visible here:
https://milwaukeedata.github.io/solid-jekyll/

The page comes up, but it doesn't seem that any of the JavaScript is working. The _config.yml file is updated. Any thoughts on why the JS isn't working? Trying to use this theme for our civic tech group's project site.

**Comment by ebonet** [comment]
Also having the same issue at [androiddevbr.github.io](androiddevbr.github.io)

**Comment by esmartwave** [comment]
My guess is something with the paths in baseurl and siteurl. The setup with the branch is different that the other themes i´ve tried for other projects.

**Comment by ebonet** [comment]
I have it working perfectly locally. However, it doesn't work online. A diffed the local html and the online one and the only difference I see is that locally is http and online I have https

**Comment by ebonet** [comment]
This is actually a duplicated issue, see #45 The solution worked for me

**Comment by esmartwave** [comment]
Thansk @ebonet that seems to work.
