### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by claudiuconstantin** [st4ple/solid-jekyll#63]
Demo [link](http://ojs.xyz/solid-jekyll/) seems to be dead now. Any new one?

**Comment by erikyuzwa** [comment]
seems to be fixed for me - http://st4ple.github.io/solid-jekyll/

**Comment by claudiuconstantin** [comment]
That's a different link, maybe it should be updated:
![image](https://user-images.githubusercontent.com/1537573/45342737-7f9d9600-b5a7-11e8-8917-548e285de1fb.png)
