### ISSUE TITLE
CSS not working in production

### ISSUE THREAD

**Issue by jaythanelam** [st4ple/solid-jekyll#64]
I'm able to edit the css and see it working in my local environment, but when I push to Github it isn't working. Everything seems to be hooked up correctly in the config file so I'm a bit lost on what's the issue here. Any help is appreciated.

Thanks_ Jaythan

**Comment by spaghettiware** [comment]
Same issue here.
Hope for a fix.
Thanks for your time!

**Comment by builtbyjordan** [comment]
Same issue here I tried the solutions proposed here : https://stackoverflow.com/questions/42450554/jekyll-site-works-locally-but-not-on-github-pages
Nothing has worked so far. 

Works locally but as soon as I push it to gh-pages the CSS is not showing up. Any help would be greatly appreciated. 
Here is a link to my site: http://supertomic.com 
Link to the my repo: https://github.com/builtbyjordan/st
Thanks in advance

**Comment by hasnogame** [comment]
Try this fix. https://github.com/Pluu/pluu.github.io/commit/d66a9ef6586e7cd207172e683721cd958ed10150
